# How to connect to JIRA?
jira_url: https://jira.abc.com # the url on your jira instance
jira_token_env_varname: jira_token
# jira_token_env_varname: for this code to execute, it requires your personal Jira token configured and set in the environment variable. 
# The 'jira_token_env_varname' config setting should have the name of the name of the environment variable in which your personal Jira token resides.

# output date format
output_date_format: yyyymmdd # the 2 support date formates are yyyymmdd & dd.mm.yyyy which will be used for the final output file
#jira board configuration file name
jira_board_config_filename: jira_board_config.yaml 