# How to connect to JIRA?
jira_url: https://jira.abc.com # the url of your jira instance

jira_token_config: 
  mode: env_var # env_var or string
  value: jira_token # if (mode = env_var) then environment variable name. if (mode = string) then personal jira token value.

# output date format
output_date_format: "%d/%m/%Y" # all python supported date format
#jira board configuration file name
jira_board_config_filename: jira_board_config.yaml 
generate_flow_metrics_report: false # true or false based on if the flow metrics reports need to be generated