boards:
- name: SAMPLE1
  jql_issue_type: "issuetype not in (Epic, Program, Test, subTaskIssueTypes())"
  board_id: 12819
- name: Jira
  jql_issue_type: "issuetype not in (Epic, Program, Test, subTaskIssueTypes())"
  board_id: 11102